"""Counterfactual explainability — structural causal model + interventions.

This module provides:
  1. SurrogateModel: maps operational variables to performance metrics
  2. CounterfactualEngine: generates interventions and ranks recommendations
  3. AttributionEngine: feature importance for backtest decisions
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor


# ─── Data classes ─────────────────────────────────────────────────────────────

@dataclass
class Intervention:
    """A single counterfactual intervention."""
    variable:        str
    original_value: float
    counterfactual_value: float
    delta:           float
    expected_metric: dict[str, float]  # metric_name -> new value
    improvement:     float              # improvement in target metric (% or absolute)
    actionable:      bool               # is this practically actionable?
    rank:            int = 0


@dataclass
class CounterfactualResult:
    """Full counterfactual analysis result."""
    backtest_run_id:   str
    target_metric:     str
    baseline_metrics:  dict[str, float]
    interventions:     list[Intervention]
    feature_importance: dict[str, float]
    summary:           str


# ─── Surrogate model ───────────────────────────────────────────────────────────

class SurrogateModel:
    """
    Lightweight surrogate model mapping operational variables → performance metrics.

    Training data is generated by running many backtests with varied operational
    parameters (latency, slippage, order_size, commission) over historical windows.

    This is a meta-model built ON TOP of the backtester — it does NOT replace it.

    Uses a formula-based approach: computes expected metric changes from
    directional sensitivities rather than fitting a GBR model to synthetic data
    (which is noisy and can learn spurious correlations).
    """

    def __init__(
        self,
        model_type: str = "gradient_boosting",
        seed: int = 42,
    ):
        self.model_type = model_type
        self.seed = seed
        self.rng = np.random.default_rng(seed)
        self._trained = False

    def fit(self, base_metrics: dict[str, float], n_samples: int = 500) -> "SurrogateModel":
        """Store base metrics for formula-based counterfactual computation."""
        self._base_metrics = base_metrics
        self._base_dd = float(base_metrics.get("max_drawdown", base_metrics.get("max_drawdown_pct", 10))) / 100
        self._base_sharpe = float(base_metrics.get("sharpe_ratio", 0.5))
        self._base_cvar = float(base_metrics.get("cvar_95", -0.01))
        self._trained = True
        self._feature_names = ["latency_ms", "slippage_bps", "order_size_pct", "commission_pct"]
        return self

    def predict(self, X: pd.DataFrame) -> dict[str, np.ndarray]:
        """
        Compute metrics from operational variables using calibrated formulas.
        Each formula captures the directional effect of operational parameters on metrics.
        """
        if not self._trained:
            raise RuntimeError("Call fit() first")

        latency  = X["latency_ms"].values
        slippage = X["slippage_bps"].values
        size_pct = X["order_size_pct"].values
        comm_pct = X["commission_pct"].values

        # Formula-based predictions calibrated so:
        # Reducing latency/size/slippage/commission → lower DD, better Sharpe/CVaR
        #
        # Positive sign = more of that variable = worse
        # Negative sign = more of that variable = better
        y_dd = (
            self._base_dd
            + 0.06  * (size_pct - 1.0)          # larger size → more DD
            + 0.004 * (slippage - 5)               # wider spread → more DD
            + 0.018 * (latency - 100) / 100       # higher latency → more DD
            + 3.0   * comm_pct                     # higher commission → more DD
        )

        # Sharpe: decreases with higher costs
        y_sharpe = (
            self._base_sharpe
            - 0.010 * (slippage - 5)               # wider spread → worse Sharpe
            - 0.080 * (size_pct - 1.0)             # larger size → worse risk-adjusted return
            - 0.400 * comm_pct                     # higher commission → worse Sharpe
        )

        # CVaR: more negative (worse) with larger positions and higher costs
        y_cvar = (
            self._base_cvar
            - 0.040 * (size_pct - 1.0)             # larger size → more tail risk
            - 0.003 * (slippage - 5)               # wider spread → worse CVaR
            - 1.500 * comm_pct                     # higher commission → worse CVaR
        )

        # No noise — deterministic formulas for reliable counterfactual predictions
        y_dd    = np.clip(y_dd,    0.005, 0.6)
        y_sharpe = np.clip(y_sharpe, -2.0, 3.0)
        y_cvar  = np.clip(y_cvar, -0.6, 0.0)

        return {
            "max_drawdown": y_dd,
            "sharpe_ratio": y_sharpe,
            "cvar_95":      y_cvar,
        }

    def get_feature_importance(self) -> dict[str, float]:
        """
        Return importance based on practical actionability and effect size.
        Order size is the biggest practical lever for traders.
        """
        if not self._trained:
            raise RuntimeError("Call fit() first")
        # Raw sensitivity (per-unit change impact on DD fraction)
        raw = {
            "commission_pct":  3.0,    # largest absolute sensitivity (but often fixed by broker)
            "order_size_pct":  0.06,   # biggest practical lever
            "slippage_bps":    0.004,   # medium impact
            "latency_ms":      0.00018, # small impact per ms (often actionable via infrastructure)
        }
        max_raw = max(raw.values())
        return {k: round(v / max_raw, 4) for k, v in raw.items()}


# ─── Counterfactual engine ─────────────────────────────────────────────────────

class CounterfactualEngine:
    """
    Generates actionable counterfactual interventions.

    For each backtest run:
      1. Train a surrogate model on synthetic operational configurations
      2. Intervene on each operational variable (increase/decrease within feasible range)
      3. Predict new metrics using the surrogate
      4. Rank by improvement and actionability
      5. Return top-k actionable recommendations
    """

    def __init__(
        self,
        surrogate_model: SurrogateModel | None = None,
        n_counterfactuals: int = 10,
        min_improvement_threshold: float = 0.005,
    ):
        self.surrogate = surrogate_model or SurrogateModel()
        self.n_cf       = n_counterfactuals
        self.min_thresh = min_improvement_threshold

    def analyze(
        self,
        backtest_result,         # BacktestResult from backtester.run()
        target_metric: str = "max_drawdown",
    ) -> CounterfactualResult:
        """
        Run full counterfactual analysis on a backtest result.

        Returns ranked actionable interventions.
        """
        base_metrics = backtest_result.metrics

        # Train surrogate
        self.surrogate.fit(base_metrics, n_samples=500)

        # Define intervention space
        intervention_defs = [
            {"variable": "latency_ms",     "base": 100.0,  "range": [50, 200],   "step": 25},
            {"variable": "slippage_bps",   "base": 5.0,    "range": [1, 20],      "step": 2},
            {"variable": "order_size_pct", "base": 1.0,   "range": [0.25, 1.5], "step": 0.25},
            {"variable": "commission_pct", "base": 0.001, "range": [0.0, 0.003], "step": 0.0005},
        ]

        interventions = []

        for defn in intervention_defs:
            var   = defn["variable"]
            base  = defn["base"]
            lo, hi = defn["range"]
            step  = defn["step"]

            for new_val in np.arange(lo, hi + step / 2, step):
                if abs(new_val - base) < 1e-9:
                    continue

                delta = new_val - base

                # Build intervention input using baseline from base_metrics
                # Derive approximate operational params from metrics profile
                base_dd_pct = base_metrics.get("max_drawdown_pct", base_metrics.get("max_drawdown", 10))
                if base_dd_pct > 15:
                    # High-risk profile: assume larger order sizes
                    base_order_size = 1.25
                    base_latency = 150.0
                    base_slippage = 8.0
                elif base_dd_pct > 8:
                    # Medium risk
                    base_order_size = 1.0
                    base_latency = 100.0
                    base_slippage = 5.0
                else:
                    # Low risk / conservative
                    base_order_size = 0.75
                    base_latency = 75.0
                    base_slippage = 3.0

                X_intervention = pd.DataFrame([{
                    "latency_ms":      base_latency,
                    "slippage_bps":    base_slippage,
                    "order_size_pct":  base_order_size,
                    "commission_pct":  0.001,
                    var: new_val,
                }])

                # Fill remaining vars with the same adaptive base values
                for v2 in ["latency_ms", "slippage_bps", "order_size_pct", "commission_pct"]:
                    if v2 not in X_intervention.columns or pd.isna(X_intervention[v2].iloc[0]):
                        X_intervention[v2] = {
                            "latency_ms": base_latency,
                            "slippage_bps": base_slippage,
                            "order_size_pct": base_order_size,
                            "commission_pct": 0.001,
                        }[v2]

                predicted = self.surrogate.predict(X_intervention)
                pred_dd   = float(predicted["max_drawdown"][0])

                # Improvement = base - predicted (lower DD is better)
                base_dd = base_metrics.get(target_metric, base_metrics.get("max_drawdown_pct", 10)) / 100
                improvement = base_dd - pred_dd

                # Actionability heuristics
                actionable = True
                if var == "latency_ms" and new_val > 200:
                    actionable = False  # high latency usually not controllable

                intervention = Intervention(
                    variable=var,
                    original_value=base,
                    counterfactual_value=float(new_val),
                    delta=float(delta),
                    expected_metric={
                        "max_drawdown": round(pred_dd * 100, 3),
                        "sharpe_ratio": round(float(predicted["sharpe_ratio"][0]), 3),
                        "cvar_95":      round(float(predicted["cvar_95"][0]) * 100, 3),
                    },
                    improvement=float(improvement),
                    actionable=actionable,
                )
                interventions.append(intervention)

        # Sort by improvement (descending)
        interventions.sort(key=lambda x: x.improvement, reverse=True)

        # Re-rank
        for i, iv in enumerate(interventions):
            iv.rank = i + 1

        # Filter actionable ones only
        actionable_ivs = [iv for iv in interventions if iv.actionable]

        # Feature importance
        feat_imp = self.surrogate.get_feature_importance()

        # Summary text
        top = next((iv for iv in actionable_ivs if iv.improvement > self.min_thresh), None)
        summary = (
            f"Reducing {top.variable} from {top.original_value} to {top.counterfactual_value} "
            f"is expected to reduce max drawdown from "
            f"{base_metrics.get('max_drawdown_pct', base_metrics.get('max_drawdown', 10)):.2f}% "
            f"to {top.expected_metric.get('max_drawdown', 0):.2f}% "
            f"(improvement: {top.improvement * 100:.2f} percentage points)"
            if top else "No significant actionable improvements found within parameter ranges."
        )

        return CounterfactualResult(
            backtest_run_id=getattr(backtest_result, "strategy_name", "unknown"),
            target_metric=target_metric,
            baseline_metrics=base_metrics,
            interventions=actionable_ivs[: self.n_cf],
            feature_importance=feat_imp,
            summary=summary,
        )

    def to_dict(self, result: CounterfactualResult) -> dict:
        """Serialize CounterfactualResult to dict for JSON."""
        return {
            "backtest_run_id":   result.backtest_run_id,
            "target_metric":     result.target_metric,
            "baseline_metrics": result.baseline_metrics,
            "interventions": [
                {
                    "variable":            iv.variable,
                    "original_value":       iv.original_value,
                    "counterfactual_value": iv.counterfactual_value,
                    "delta":               iv.delta,
                    "expected_metric":     iv.expected_metric,
                    "improvement":          round(iv.improvement * 100, 3),
                    "actionable":           iv.actionable,
                    "rank":                 iv.rank,
                }
                for iv in result.interventions
            ],
            "feature_importance": {
                k: round(v, 4) for k, v in result.feature_importance.items()
            },
            "summary": result.summary,
        }
