import streamlit as st

def render():
    st.title("ℹ️ About Stock-AIML")
    st.markdown(
        """
        Welcome to **Stock-AIML**, a production-grade, modular deep learning backtesting and strategy optimization platform. 
        This platform bridges the gap between traditional algorithmic trading and modern artificial intelligence capabilities.
        """
    )
    
    st.divider()

    # --- Section: Why this project? / How it helps ---
    st.header("🎯 Purpose & Vision")
    st.markdown(
        """
        **Stock-AIML** is a next-generation algorithmic trading and portfolio optimization platform that bridges the gap between state-of-the-art Artificial Intelligence research and applied financial markets. 

        Our vision is to empower quants, researchers, and traders with a highly autonomous, transparent, and resilient trading ecosystem. By moving beyond traditional predictive models, Stock-AIML builds strategies that not only adapt to ever-changing market dynamics but also explain their reasoning and withstand extreme market shocks.

        ### 🚀 Core Technologies & Innovations
        
        The platform achieves its vision through an advanced, multi-paradigm Machine Learning architecture:

        *   **Temporal Graph Neural Networks (TGNNs):** 
            We leverage TGNNs to capture the complex, hidden spatial-temporal dependencies across the market. By treating stocks as interconnected nodes and tracking their relationships over time, the platform identifies cascading market movements and cross-asset correlations that traditional models miss.
            
        *   **Reinforcement Learning (RL) for Optimization:** 
            Markets are dynamic environments. Our continuous Deep Reinforcement Learning agents optimize trade execution and portfolio rebalancing on the fly, maximizing cumulative returns while penalizing excessive risk and transaction costs.
            
        *   **Adversarial Scenario Generation (Stress Testing):** 
            To ensure our strategies are truly robust, we utilize Generative Adversarial Networks (GANs) and rule-based market generators (AMG) to synthesize extreme "black-swan" market conditions (liquidity shocks, correlated selloffs, volatility spikes). By continuously stress-testing our models against these adversarial scenarios, we minimize downside risk and prevent edge-case failures.
            
        *   **Counterfactual & Causal ML (Explainable AI - XAI):** 
            Trust requires transparency. Rather than relying on black-box predictions, our platform employs Counterfactual and Causal structural modeling. This allows users to ask "What if?"—understanding exactly *why* a strategy made certain decisions, what caused a specific outcome, and how tweaking different market variables (like slippage or commission) would have altered the system's performance.
        """
    )

    st.divider()

    # --- Section: Navigation Guide ---
    st.header("🧭 Navigation Guide")
    st.info("Here is a breakdown of what you can do in each section of the application:")

    col1, col2 = st.columns(2)
    with col1:
        with st.expander("📁 Dataset Upload"):
            st.write("Upload your historical OHLCV (Open, High, Low, Close, Volume) CSV files. The system automatically aligns time series and generates essential technical indicators without lookahead bias.")
        with st.expander("⚙️ Strategy Config"):
            st.write("Tune the parameters of your chosen trading strategy (e.g., RSI thresholds for Momentum, or Z-score thresholds for Mean Reversion).")
        with st.expander("▶️ Run Backtest"):
            st.write("Execute your strategy over the historical data. The backtester tracks positions, simulates fills, and computes the equity curve live.")
        with st.expander("📊 Results Summary"):
            st.write("Analyze deep performance metrics like Annualized Return, Sharpe Ratio, Sortino Ratio, Max Drawdown, and Conditional Value at Risk (CVaR).")
        with st.expander("⚡ Stress Test"):
            st.write("Subject your strategy to synthetic adversarial scenarios generated by AI, such as 'Correlated Selloffs' or 'Liquidity Shocks'.")

    with col2:
        with st.expander("🔍 Explanation"):
            st.write("Utilize Counterfactual Analysis to get plain-English reasoning on strategy performance. E.g., 'If slippage was 2 bps lower, your drawdown would shrink by 15%'.")
        with st.expander("📤 Export"):
            st.write("Download your full backtest results, trade logs, and metrics as CSV or JSON for external auditing.")
        with st.expander("📚 API Docs"):
            st.write("Access the interactive Swagger UI. Stock-AIML backend is powered by FastAPI, so every dashboard action can also be triggered programmatically.")
        with st.expander("🧪 MLflow Tracking"):
            st.write("Track the training curves, loss metrics, and hyperparameters of the deep learning models (like the TGNN and RL agent).")

    st.divider()

    # --- Section: Future Scope ---
    st.header("🚀 Future Scope & Roadmap")
    st.write("Stock-AIML is constantly evolving. Planned future enhancements include:")
    
    st.markdown(
        """
        1. **Real-Time Broker Integration:** Connecting the execution surrogate directly to live brokers like Interactive Brokers (IBKR), Alpaca, or Binance for paper and live trading.
        2. **Tick-Level Simulation:** Upgrading from bar-level (OHLCV) simulations to Level-2 order book (tick-by-tick) granularity for high-frequency trading (HFT) modeling.
        3. **LLM Sentiment Engine:** Integrating Large Language Models (LLMs) to ingest live financial news and SEC filings into the TGNN graph edges.
        4. **Multi-Agent Reinforcement Learning:** Training multiple competing AI agents to balance a large multi-asset portfolio dynamically.
        """
    )
    
    st.caption("Developed with ❤️ for Quantitative Researchers & AI Enthusiasts.")